# Generated by Django 4.1.7 on 2023-06-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_alter_files_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
